### ISSUE TITLE
Question about netmap binding to ixgbe

### ISSUE THREAD

**Issue by morphyno** [pavel-odintsov/ixgbe-linux-netmap#10]
I have compiled the patched 3.23.2.1 driver and netmap.ko
However, when I loaded the modules in order of netmap.ko, and ixgbe.ko, I notice that ixgbe is not binded to netmap (or vice versa)

$ lsmod | grep -i netmap
netmap                139720  0
$ lsmod | grep -i ixgbe
ixgbe                 262236  0
dca                    15130  1 ixgbe
ptp                    18933  2 ixgbe,e1000e

Is this expected, on my other boxes running older version of netmap and ixgbe, the two modules are binded 

$ lsmod | grep -i ixgbe
ixgbe                 237798  0 
netmap                114576  1 ixgbe
dca                    15130  1 ixgbe
mdio                   13807  1 ixgbe
ptp                    18933  2 tg3,ixgbe

**Comment by pavel-odintsov** [comment]
Hello!

What you mean by "binded" ? If you haven't netmap module loaded you can't load patched ixgbe driver because it depends on symbols exported by netmap.

dca and ptp are optional features and not required in all versions. 

Just do rmmod netmap and try to load ixgbe. If it success you are using incorrect (not patched) version of ixgbe :)

I prefer to use insmod instead of modprobe for this case.

**Comment by morphyno** [comment]
It looks like ixgbe-3.23.2.1 is already patched with netmap, so I should be able to just run "make", right?
But yet I can load it without netmap being loaded. Am I missing some steps here?

**Comment by morphyno** [comment]
Hi @pavel-odintsov, looks like everything is working great! I came from a much older version of netmap, looks like the module binding between the two modules are no longer there. On older versions,  it use to be like this:

`$ lsmod | grep -i ixgbe
ixgbe 237798 0 
netmap 114576 1 ixgbe
dca 15130 1 ixgbe
mdio 13807 1 ixgbe
ptp 18933 2 tg3,ixgbe`

And I actually had code to check for that dependency, so now thats' no longer necessary.

**Comment by pavel-odintsov** [comment]
Oh, yeah. I haven't saw something like this few yeas :)
