### ISSUE TITLE
driver can not be loaded

### ISSUE THREAD

**Issue by Groundsea** [pavel-odintsov/ixgbe-linux-netmap#5]
Hi expert,

I merged patch to 3.23.2.1 and 4.0.3, but both can not work, when I execute insmod ixgbe.ko, it report "insmod: ERROR: could not insert module ixgbe.ko: Invalid parameters". 

My operation is like below, please help to check is something incorrect? Thank you very much!
1. added #define CONFIG_NETMAP_MODULE in ixgbe_main.c, so the driver will include the netmap code.
2. delete "char ixgbe_driver_name[] = "ixgbe";" in ixgbe_main.c because it is defined in netmap.
3. modified Makefile to add the head files path of netmap.

Then after compile, it will report:
WARNING: "netmap_attach" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "netmap_rx_irq" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "netmap_no_pendintr" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "netmap_ring_reinit" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "netmap_detach" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "netmap_disable_all_rings" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "netmap_reset" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "ixgbe_driver_name" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!
WARNING: "netmap_enable_all_rings" [/root/ixgbe/ixgbe-3.23.2.1/src/ixgbe.ko] undefined!

but the ixgeb.ko can be generated. then when I try to insmod, I only get "insmod: ERROR: could not insert module ixgbe.ko: Invalid parameters". 

Thank you very much!

Regards,
Haifeng.

**Comment by pavel-odintsov** [comment]
Hello!

Thanks for interest! I could recommend you this reference: http://www.stableit.ru/2014/10/netmap-debian-7-wheezy-intel-82599.html as more reliable way to run custom driver with netmap.

Looks like you lost about modprobe netmap before modprobe ixgbe.

**Comment by Groundsea** [comment]
Hi expert,

Thank you for your answer, currently the driver can be loaded, but when I begin ping-pong test, it seemed receive side didn't receive the packets.

My procedure is like below:
cd netmap/LINUX/

sed -i 's/#define ixgbe_driver_name netmap_ixgbe_driver_name/\/\/\0/' ixgbe_netmap_linux.h 
sed -i 's/^char ixgbe_driver_name\[\]/\/\/\0/' ixgbe_netmap_linux.h

vi ixgbe-override

ixgbe-dst := ixgbe
ixgbe-patch := #(leave empty) 
ixgbe-src := /usr/src/ixgbe-linux-netmap/ixgbe-3.23.2.1/src/

./configure  --override=ixgbe-override --drivers=ixgbe
make

rmmod ixgbe

insmod /usr/src/netmap/LINUX/netmap.ko 
insmod /usr/src/netmap/LINUX/ixgbe/ixgbe.ko

make KSRC=/lib/modules/3.10.0-229.4.2.el7.x86_64/source apps

The print information on receive side:
[root@controller build-apps(keystone_admin)]# ./pkt-gen -i ens2f1 -f rx
425.736280 main [1830] interface is ens2f1
425.736357 main [1941] running on 1 cpus (have 32)
425.738643 extract_ip_range [362] range is 10.0.0.1:0 to 10.0.0.1:0
425.738649 extract_ip_range [362] range is 10.1.0.1:0 to 10.1.0.1:0
425.836906 main [2039] mapped 334980KB at 0x7f9ff5987000
Receiving from netmap:ens2f1: 32 queues, 1 threads and 1 cpus.
425.836938 main [2126] Wait 2 secs for phy reset
427.837067 main [2128] Ready...
427.837175 receiver_body [1331] reading from netmap:ens2f1 fd 3 main_fd 3
428.838140 main_thread [1620] 2.000 pps (2.000 pkts 3.576 Kbps in 1001011 usec) 2.00 avg_batch
429.839177 main_thread [1620] 1.000 pps (1.000 pkts 952.000 bps in 1001038 usec) 1.00 avg_batch
430.840068 main_thread [1620] 0.000 pps (0.000 pkts 0.000 bps in 1000891 usec) 0.00 avg_batch
431.841107 main_thread [1620] 1.000 pps (1.000 pkts 952.000 bps in 1001039 usec) 1.00 avg_batch
432.842150 main_thread [1620] 0.000 pps (0.000 pkts 0.000 bps in 1001043 usec) 0.00 avg_batch
433.843178 main_thread [1620] 1.000 pps (1.000 pkts 952.000 bps in 1001028 usec) 1.00 avg_batch
434.844204 main_thread [1620] 0.000 pps (0.000 pkts 0.000 bps in 1001025 usec) 0.00 avg_batch
435.845227 main_thread [1620] 1.000 pps (1.000 pkts 952.000 bps in 1001024 usec) 1.00 avg_batch
436.846083 main_thread [1620] 0.000 pps (0.000 pkts 0.000 bps in 1000855 usec) 0.00 avg_batch
437.847136 main_thread [1620] 1.000 pps (1.000 pkts 952.000 bps in 1001054 usec) 1.00 avg_batch

The print information on send side:
[root@controller build-apps(keystone_admin)]# ./pkt-gen -i ens2f1 -f tx
443.056401 main [1830] interface is ens2f1
443.056476 main [1941] running on 1 cpus (have 32)
443.058779 extract_ip_range [362] range is 10.0.0.1:0 to 10.0.0.1:0
443.058784 extract_ip_range [362] range is 10.1.0.1:0 to 10.1.0.1:0
443.058830 main [2039] mapped 334980KB at 0x7f8430f35000
Sending on netmap:ens2f1: 32 queues, 1 threads and 1 cpus.
10.0.0.1 -> 10.1.0.1 (00:00:00:00:00:00 -> ff:ff:ff:ff:ff:ff)
443.058845 main [2124] Sending 512 packets every  0.000000000 s
443.058847 main [2126] Wait 2 secs for phy reset
445.058909 main [2128] Ready...
445.059040 sender_body [1140] start, fd 3 main_fd 3
445.253795 sender_body [1218] drop copy
446.060002 main_thread [1620] 391.469 Kpps (391.869 Kpkts 188.097 Mbps in 1001021 usec) 77.49 avg_batch
447.061058 main_thread [1620] 401.907 Kpps (402.331 Kpkts 193.119 Mbps in 1001055 usec) 120.28 avg_batch
448.062028 main_thread [1620] 370.893 Kpps (371.253 Kpkts 178.201 Mbps in 1000971 usec) 73.00 avg_batch
449.063064 main_thread [1620] 328.411 Kpps (328.751 Kpkts 157.800 Mbps in 1001035 usec) 48.55 avg_batch
450.064094 main_thread [1620] 318.392 Kpps (318.720 Kpkts 152.986 Mbps in 1001030 usec) 48.47 avg_batch
451.065122 main_thread [1620] 316.852 Kpps (317.178 Kpkts 152.245 Mbps in 1001028 usec) 41.46 avg_batch
452.066164 main_thread [1620] 306.889 Kpps (307.209 Kpkts 147.460 Mbps in 1001042 usec) 34.12 avg_batch
453.067207 main_thread [1620] 298.423 Kpps (298.734 Kpkts 143.392 Mbps in 1001043 usec) 38.56 avg_batch

Do you know the reason of such phenomenon?

Thank you very much!

Regards,
Haifeng.

**Comment by pavel-odintsov** [comment]
Hi!

Could you try enable promisc mode for interface?

**Comment by Groundsea** [comment]
Hi expert,

Yes, I have already enable promisc mode.

[root@controller build-apps(keystone_admin)]# ifconfig ens2f1
ens2f1: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet6 fe80::3aea:a7ff:fe17:1d85  prefixlen 64  scopeid 0x20<link>
        ether 38:ea:a7:17:1d:85  txqueuelen 1000  (Ethernet)
        RX packets 2088  bytes 275851 (269.3 KiB)
        RX errors 0  dropped 129  overruns 0  frame 0
        TX packets 9211861  bytes 552711828 (527.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by Groundsea** [comment]
[root@controller build-apps(keystone_admin)]# ifconfig ens2f1
ens2f1: flags=4419<UP,BROADCAST,RUNNING,PROMISC,MULTICAST>  mtu 1500
        inet6 fe80::3aea:a7ff:fe17:1d85  prefixlen 64  scopeid 0x20<link>
        ether 38:ea:a7:17:1d:85  txqueuelen 1000  (Ethernet)
        RX packets 2128  bytes 281029 (274.4 KiB)
        RX errors 0  dropped 131  overruns 0  frame 0
        TX packets 9211861  bytes 552711828 (527.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by pavel-odintsov** [comment]
Do you have any switches between machines? Could you use direct cable?

**Comment by Groundsea** [comment]
Er.... I'm sorry, It seemed I miss-understood the ping-pong test. I think it use the same NIC on the same blade, with 2 processes, one for rx and one for tx.

**Comment by pavel-odintsov** [comment]
I'm never try it this way. I'm using separate servers connected with direct cable. Switch connection is OK too but in this case you could keep your eyes on correct mac addresses :)

**Comment by Groundsea** [comment]
Thank you very much! Now I use 2 blades, connect with switch, the receive side can get the packets.

But do you know, the previous test mode "use the same NIC on the same blade", is possible or not?

**Comment by pavel-odintsov** [comment]
So I suppose it's NIC feature and it named as "hardware loopback". But I never use it.

**Comment by Groundsea** [comment]
Thank you very much!

**Comment by Groundsea** [comment]
Hi Pavel,

It seemed the netmap team very busy, could you please help to see such issue?

Thank you very much!

https://github.com/luigirizzo/netmap/issues/79

**Comment by pavel-odintsov** [comment]
Hello!

Could you share cat /proc/cpuinfo, perf top output and htop output when you capturing packets. 

You could try to use my code instead pkt-gen:
https://github.com/FastVPSEestiOu/fastnetmon/blob/master/src/tests/build_netmap.bash and https://github.com/FastVPSEestiOu/fastnetmon/blob/master/src/tests/netmap.cpp

It's working really well and support multiple queues.

**Comment by pavel-odintsov** [comment]
Close because original issue have solved.
