### ISSUE TITLE
An issue on ixgbe-linux-netmap 

### ISSUE THREAD

**Issue by kaiaixi** [pavel-odintsov/ixgbe-linux-netmap#6]
Hi, 

I am using ixgbe-4.1.5 from your github. 
After compiling the codes, I receive "Unknown symbol in module" when I insmod the ko.

Ubuntu 14.04 64bit LTS
 3.13.0-77-generic

**Comment by pavel-odintsov** [comment]
Hello

Please share dmesg output.

On Sunday, 21 February 2016, kaiaixi <notifications@github.com> wrote:

> Hi,
>
> I am using ixgbe-4.1.5 from your github.
> After compiling the codes, I receive "Unknown symbol in module" when I
> insmod the ko.
>
> Ubuntu 14.04 64bit LTS
> 3.13.0-77-generic
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/ixgbe-linux-netmap/issues/6>.
>


-- 
Sincerely yours, Pavel Odintsov

**Comment by kaiaixi** [comment]
Hi, Pavel

[ 7207.213089] ixgbe: module verification failed: signature and/or
 required key missing - tainting kernel
[ 7207.213631] ixgbe: Unknown symbol vxlan_get_rx_port (err 0)


On Sun, Feb 21, 2016 at 5:45 PM, Pavel Odintsov <notifications@github.com>
wrote:

> Hello
>
> Please share dmesg output.
>
> On Sunday, 21 February 2016, kaiaixi <notifications@github.com> wrote:
>
> > Hi,
> >
> > I am using ixgbe-4.1.5 from your github.
> > After compiling the codes, I receive "Unknown symbol in module" when I
> > insmod the ko.
> >
> > Ubuntu 14.04 64bit LTS
> > 3.13.0-77-generic
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/pavel-odintsov/ixgbe-linux-netmap/issues/6>.
> >
>
>
> --
> Sincerely yours, Pavel Odintsov
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/ixgbe-linux-netmap/issues/6#issuecomment-186783849>
> .
>



-- 

Regards,

Royce Niu

---------------------------------------
kaiaixi@gmail.com

**Comment by pavel-odintsov** [comment]
What about modprobe vxlan?

**Comment by kaiaixi** [comment]
Works!
Thank you : >

**Comment by pavel-odintsov** [comment]
Welcome! ;)

On Sunday, 21 February 2016, kaiaixi <notifications@github.com> wrote:

> Works!
> Thank you : >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/ixgbe-linux-netmap/issues/6#issuecomment-186835470>
> .
>


-- 
Sincerely yours, Pavel Odintsov
