### ISSUE TITLE
Unable to build ixgbe-4.1.5 module after latest commit

### ISSUE THREAD

**Issue by morphyno** [pavel-odintsov/ixgbe-linux-netmap#9]
/home/devuser/netmap/ixgbe-linux-netmap/ixgbe-4.1.5/src/ixgbe_main.c:9641:2: error: unknown field ‘ndo_set_tx_maxrate’ specified in initializer
  .ndo_set_tx_maxrate = ixgbe_tx_maxrate,

**Comment by pavel-odintsov** [comment]
Forwarded to patch author: https://github.com/pavel-odintsov/ixgbe-linux-netmap/pull/8 Just try to use version without this patch.

**Comment by atomnuker** [comment]
morphyno: what kernel version are you trying to compile for? Seems like it's too old. You should probably use the 3.23 version.

**Comment by morphyno** [comment]
Yea, i'm on 3.10, I'm building this on CentOS 7.1, which is our development environment.

**Comment by atomnuker** [comment]
Yeah, that's practically ancient. Comment out the entire line ".ndo_set_tx_maxrate = ixgbe_tx_maxrate," if you insist on using 4.1.5. Or use ixgbe-3.23 instead of ixgbe-4.1.5. Or upgrade your kernel.
Point is, as far as I understand, ixgbe-4.1.5 is for linux kernels released after 4.1.5. Support for kernels before that is provided by ixgbe-3.23. Support for kernels even older than that is up to you.

**Comment by morphyno** [comment]
Thanks @atomnuker, I will use ixgbe 3.23, thank you!

**Comment by morphyno** [comment]
@pavel-odintsov, I did revert @atomnuker 's change and the module build fine. One thing I am noticing is very slow performance using pkt-gen for 64 byte frames, I am getting about 1.4 Million fps vs 14 Million. Is this something you've observed as well?

**Comment by pavel-odintsov** [comment]
No, it's not OK. pkg-get could generate up to 12-14 mpps without any issues.

**Comment by morphyno** [comment]
When I use the ixgbe build from netmap's repo, i can get 7~8 mpps. Am I missing something? Do I have to do anything else other than running "make" ?

**Comment by pavel-odintsov** [comment]
Definitely yes! Full guide it a bit complicated: http://www.stableit.ru/2014/10/netmap-debian-7-wheezy-intel-82599.html

**Comment by morphyno** [comment]
Hey @pavel-odintsov, thanks for the guide. Everything is working wonderfully. I wonder did you have to do anything additional to your patch. For some reason, recent netmap git's ixgbe is causing my kernel (CentOS 7) to crash every-time I put the interface in netmap receive mode.

**Comment by morphyno** [comment]
Btw, the netmap and ixgbe binding still shows from the output of "lsmod"

`sudo lsmod | grep -i ixgbe
ixgbe                 306058  0
netmap                139720  1 ixgbe
vxlan                  37409  1 ixgbe
dca                    15130  1 ixgbe
ptp                    18933  2 ixgbe,e1000e`

**Comment by pavel-odintsov** [comment]
Hello!

No I do not do anything else.  I just apply netmap patch on this code. Just share kernel error with netmap developers. I could not help here.

**Comment by morphyno** [comment]
But why do you have to remove these #define?

sed -i 's/#define ixgbe_driver_name netmap_ixgbe_driver_name/\/\/\0/' ixgbe_netmap_linux.h 
sed -i 's/^char ixgbe_driver_name\[\]/\/\/\0/' ixgbe_netmap_linux.h

**Comment by pavel-odintsov** [comment]
Same issue from my side with 3.19.0-25-generic. Could we make some version check here and disable this code for oldest kernels?

**Comment by pavel-odintsov** [comment]
Because they also defined in netmap sources and will be conflict.

On Thu, Mar 10, 2016 at 3:53 PM, Morgan Yang <notifications@github.com>
wrote:

> But why do you have to remove these #define?
>
> sed -i 's/#define ixgbe_driver_name netmap_ixgbe_driver_name/\/\/\0/'
> ixgbe_netmap_linux.h
> sed -i 's/^char ixgbe_driver_name[]/\/\/\0/' ixgbe_netmap_linux.h
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pavel-odintsov/ixgbe-linux-netmap/issues/9#issuecomment-194829873>
> .
>



-- 
Sincerely yours, Pavel Odintsov

**Comment by morphyno** [comment]
Got it, thanks!
